-- seed_18_verbal_batch2.sql
-- Continues the Verbal Ability expansion. Adds 25 questions each for
-- Para Jumbles, Reading Comprehension, and Fill in the Blanks -- the
-- three Verbal Ability topics that had zero questions. This completes
-- the entire Verbal Ability category at 25+ questions per topic.
-- Reading Comprehension passages are short and repeated within each
-- self-contained question, since this schema has no separate passage
-- table (each question is independent question_text + 4 options).
-- Additive only; safe to run once after seed_17_verbal_batch1.sql.

-- ============================================================
-- Verbal Ability > Para Jumbles
-- ============================================================
insert into public.questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
select id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_option, q.explanation, q.difficulty
from public.topics, (values
  ('Arrange the sentences in the correct order. P: They decided to postpone the trip. Q: The weather forecast predicted heavy rain. R: The picnic was planned for Sunday. S: Everyone was disappointed but understood the reason.', 'RQPS', 'RPQS', 'QRPS', 'RQSP', 'a', 'Logical order: the picnic is planned, rain is forecast, the trip is postponed, and everyone reacts.', 'medium'),
  ('Arrange the sentences in the correct order. P: He immediately called for an ambulance. Q: The man suddenly collapsed on the street. R: Passersby gathered around in concern. S: The ambulance arrived within minutes and took him to the hospital.', 'QPRS', 'QRPS', 'RQPS', 'QRSP', 'b', 'Logical order: he collapses, people gather, help is called, and the ambulance arrives.', 'medium'),
  ('Arrange the sentences in the correct order. P: As a result, sales increased by 30%. Q: The company launched a new marketing campaign. R: The campaign focused on social media platforms. S: Customer engagement improved significantly.', 'QRSP', 'QRPS', 'RQSP', 'QSRP', 'a', 'Logical order: campaign launched, its focus described, engagement improves, sales rise as a result.', 'medium'),
  ('Arrange the sentences in the correct order. P: She studied hard for months. Q: Finally, the results were declared. R: Priya wanted to become a doctor. S: She scored well and got admission into a medical college.', 'RPQS', 'PRQS', 'RQPS', 'RPSQ', 'a', 'Logical order: goal stated, she studies, results come out, and she gets admission.', 'medium'),
  ('Arrange the sentences in the correct order. P: The bridge was closed for repairs. Q: Commuters faced long delays. R: An alternate route was suggested by the traffic police. S: This caused heavy traffic congestion nearby.', 'PSQR', 'PQSR', 'SPQR', 'PSRQ', 'a', 'Logical order: bridge closes, congestion follows, commuters face delays, police suggest an alternate route.', 'hard'),
  ('Arrange the sentences in the correct order. P: The chef prepared a special dish. Q: Guests praised the flavors. R: A famous food critic was invited to the restaurant. S: The dish became the restaurant''s signature item.', 'RPQS', 'PRQS', 'RQPS', 'RPSQ', 'a', 'Logical order: critic invited, chef prepares dish, guests praise it, it becomes signature item.', 'medium'),
  ('Arrange the sentences in the correct order. P: The team practiced rigorously every day. Q: They won the championship. R: The coach set high goals for the season. S: Their hard work paid off in the finals.', 'RPSQ', 'RPQS', 'PRSQ', 'RSPQ', 'a', 'Logical order: goals set, practice follows, hard work pays off, championship won.', 'medium'),
  ('Arrange the sentences in the correct order. P: The scientist conducted several experiments. Q: The hypothesis was finally confirmed. R: She noticed an unusual pattern in the data. S: Further tests were designed to explore this pattern.', 'PRSQ', 'PRQS', 'RPSQ', 'PSRQ', 'b', 'Logical order: experiments conducted, pattern noticed, further tests designed, hypothesis confirmed.', 'medium'),
  ('Arrange the sentences in the correct order. P: He packed his bags the night before. Q: Ravi was excited about his first trip abroad. R: He reached the airport three hours early. S: The flight was delayed by two hours.', 'QPRS', 'PQRS', 'QRPS', 'QPSR', 'a', 'Logical order: excitement described, packing, reaching the airport, then the delay.', 'medium'),
  ('Arrange the sentences in the correct order. P: The river overflowed its banks. Q: Heavy rains continued for three days. R: Rescue teams were deployed immediately. S: Several low-lying areas were flooded.', 'QPSR', 'QPRS', 'PQSR', 'QSPR', 'a', 'Logical order: rains continue, river overflows, areas flood, rescue teams deployed.', 'medium'),
  ('Arrange the sentences in the correct order. P: The library extended its working hours. Q: More students began visiting during exam season. R: Students often complained about limited study time. S: This decision was welcomed by many.', 'RPSQ', 'RPQS', 'PRSQ', 'RSPQ', 'b', 'Logical order: complaints about limited time, hours extended, decision welcomed, more students visit.', 'hard'),
  ('Arrange the sentences in the correct order. P: The startup secured a major investment. Q: The founders had pitched their idea for months. R: They used the funds to expand their team. S: The company grew rapidly within a year.', 'QPRS', 'PQRS', 'QRPS', 'QPSR', 'a', 'Logical order: founders pitch for months, investment secured, funds used to expand, company grows.', 'medium'),
  ('Arrange the sentences in the correct order. P: The old bridge was demolished. Q: A new, wider bridge was constructed in its place. R: Engineers found structural cracks during inspection. S: Traffic flow improved significantly afterward.', 'RPQS', 'PRQS', 'RQPS', 'RPSQ', 'a', 'Logical order: cracks found, old bridge demolished, new bridge built, traffic improves.', 'medium'),
  ('Arrange the sentences in the correct order. P: The teacher explained the concept with examples. Q: Students still had doubts after the lecture. R: A follow-up session was arranged the next day. S: Most students understood clearly after the second session.', 'PQRS', 'QPRS', 'PRQS', 'PQSR', 'a', 'Logical order: explanation given, doubts remain, follow-up arranged, understanding achieved.', 'medium'),
  ('Arrange the sentences in the correct order. P: The company faced a data breach. Q: Customer trust was affected initially. R: Security experts were hired to investigate. S: New security protocols were implemented successfully.', 'PQRS', 'QPRS', 'PRQS', 'PQSR', 'a', 'Logical order: breach occurs, trust affected, experts hired, new protocols implemented.', 'medium'),
  ('Arrange the sentences in the correct order. P: The government announced a new policy. Q: Citizens debated its potential impact. R: Experts were invited to explain the details. S: The policy was implemented after public consultation.', 'PRQS', 'PQRS', 'RPQS', 'PRSQ', 'a', 'Logical order: policy announced, experts explain, citizens debate, policy implemented after consultation.', 'medium'),
  ('Arrange the sentences in the correct order. P: The plane began to descend. Q: Passengers fastened their seatbelts. R: An announcement was made about landing. S: The plane landed safely on the runway.', 'RQPS', 'QRPS', 'RPQS', 'RQSP', 'a', 'Logical order: announcement made, seatbelts fastened, descent begins, plane lands.', 'medium'),
  ('Arrange the sentences in the correct order. P: The farmer planted seeds early in the season. Q: A good harvest followed the timely rains. R: Timely rains supported healthy growth. S: The farmer sold the produce at a good price.', 'PRQS', 'PQRS', 'RPQS', 'PRSQ', 'a', 'Logical order: seeds planted, rains support growth, good harvest follows, produce sold.', 'medium'),
  ('Arrange the sentences in the correct order. P: The museum unveiled a new exhibit. Q: Visitors flocked to see the rare artifacts. R: The exhibit featured artifacts from ancient civilizations. S: Positive reviews spread quickly online.', 'PRQS', 'PQRS', 'RPQS', 'PRSQ', 'a', 'Logical order: exhibit unveiled, its content described, visitors flock, reviews spread.', 'medium'),
  ('Arrange the sentences in the correct order. P: The company introduced a four-day work week. Q: Employees reported higher job satisfaction. R: Productivity levels remained stable. S: Other companies began considering similar policies.', 'PQRS', 'QPRS', 'PRQS', 'PQSR', 'a', 'Logical order: policy introduced, satisfaction rises, productivity holds steady, other companies take note.', 'medium'),
  ('Arrange the sentences in the correct order. P: The volunteers cleaned the beach on Saturday. Q: Local authorities praised their initiative. R: Plastic waste had accumulated over months. S: The beach looked pristine afterward.', 'RPSQ', 'PRSQ', 'RPQS', 'RSPQ', 'a', 'Logical order: waste accumulates, volunteers clean, beach looks pristine, authorities praise them.', 'medium'),
  ('Arrange the sentences in the correct order. P: The negotiations lasted several hours. Q: Both parties reached a mutual agreement. R: Tensions had been rising between the two companies. S: The agreement was signed the following week.', 'RPQS', 'PRQS', 'RQPS', 'RPSQ', 'a', 'Logical order: tensions rise, negotiations occur, agreement reached, agreement signed later.', 'medium'),
  ('Arrange the sentences in the correct order. P: The artist spent years perfecting her technique. Q: Critics praised the exhibition widely. R: Her first major exhibition opened downtown. S: Word of her talent spread quickly.', 'PRQS', 'PQRS', 'RPQS', 'PRSQ', 'a', 'Logical order: years of practice, exhibition opens, critics praise it, word spreads.', 'medium'),
  ('Arrange the sentences in the correct order. P: The company relocated its headquarters. Q: Employees were offered relocation packages. R: The old office had become too small. S: Productivity improved in the new space.', 'RQPS', 'RPQS', 'QRPS', 'RQSP', 'a', 'Logical order: office too small, packages offered, company relocates, productivity improves.', 'medium'),
  ('Arrange the sentences in the correct order. P: The chef sourced fresh ingredients locally. Q: The restaurant gained a loyal following. R: A new restaurant opened in town. S: Diners praised the quality of the food.', 'RPSQ', 'PRSQ', 'RPQS', 'RSPQ', 'a', 'Logical order: restaurant opens, chef sources ingredients, diners praise the food, loyal following develops.', 'medium')
) as q(question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
where topics.slug = 'para-jumbles';

-- ============================================================
-- Verbal Ability > Reading Comprehension
-- ============================================================
insert into public.questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
select id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_option, q.explanation, q.difficulty
from public.topics, (values
  ('Passage: "Renewable energy sources like solar and wind power have become increasingly affordable over the past decade. Many countries are now investing heavily in these technologies to reduce their dependence on fossil fuels. However, challenges remain, including the need for efficient energy storage solutions and upgraded electrical grids." Question: What has happened to the cost of renewable energy over the past decade?', 'Increased', 'Decreased', 'Remained stable', 'Fluctuated wildly', 'b', 'The passage states renewable energy "has become increasingly affordable", meaning its cost decreased.', 'easy'),
  ('Passage: "Renewable energy sources like solar and wind power have become increasingly affordable over the past decade. Many countries are now investing heavily in these technologies to reduce their dependence on fossil fuels. However, challenges remain, including the need for efficient energy storage solutions and upgraded electrical grids." Question: What is one challenge mentioned regarding renewable energy?', 'Lack of sunlight', 'Efficient energy storage solutions', 'High population', 'Lack of investment', 'b', 'The passage explicitly names energy storage as a remaining challenge.', 'easy'),
  ('Passage: "Renewable energy sources like solar and wind power have become increasingly affordable over the past decade. Many countries are now investing heavily in these technologies to reduce their dependence on fossil fuels. However, challenges remain, including the need for efficient energy storage solutions and upgraded electrical grids." Question: Why are countries investing in renewable energy, according to the passage?', 'To reduce dependence on fossil fuels', 'To increase electricity prices', 'To reduce population', 'To improve tourism', 'a', 'The passage states the investment aims "to reduce their dependence on fossil fuels".', 'easy'),
  ('Passage: "Renewable energy sources like solar and wind power have become increasingly affordable over the past decade. Many countries are now investing heavily in these technologies to reduce their dependence on fossil fuels. However, challenges remain, including the need for efficient energy storage solutions and upgraded electrical grids." Question: Which energy sources are given as examples in the passage?', 'Solar and wind', 'Coal and oil', 'Nuclear and hydro', 'Gas and coal', 'a', 'The passage explicitly names "solar and wind power" as examples.', 'easy'),
  ('Passage: "Renewable energy sources like solar and wind power have become increasingly affordable over the past decade. Many countries are now investing heavily in these technologies to reduce their dependence on fossil fuels. However, challenges remain, including the need for efficient energy storage solutions and upgraded electrical grids." Question: What do electrical grids need, according to the passage?', 'To be shut down', 'Upgrades to handle variable power generation', 'To be privatized', 'To be reduced in number', 'b', 'The passage mentions the need for "upgraded electrical grids".', 'medium'),
  ('Passage: "The human brain contains approximately 86 billion neurons, each connected to thousands of others through synapses. This vast network allows the brain to process information, store memories, and control bodily functions. Recent research suggests the brain continues to form new neural connections throughout a person''s life, a phenomenon known as neuroplasticity." Question: How many neurons does the human brain contain?', '86 million', '86 billion', '8.6 billion', '860 million', 'b', 'The passage states "approximately 86 billion neurons".', 'easy'),
  ('Passage: "The human brain contains approximately 86 billion neurons, each connected to thousands of others through synapses. This vast network allows the brain to process information, store memories, and control bodily functions. Recent research suggests the brain continues to form new neural connections throughout a person''s life, a phenomenon known as neuroplasticity." Question: What connects neurons to each other, according to the passage?', 'Synapses', 'Arteries', 'Muscles', 'Tissues', 'a', 'The passage states neurons are "connected to thousands of others through synapses".', 'easy'),
  ('Passage: "The human brain contains approximately 86 billion neurons, each connected to thousands of others through synapses. This vast network allows the brain to process information, store memories, and control bodily functions. Recent research suggests the brain continues to form new neural connections throughout a person''s life, a phenomenon known as neuroplasticity." Question: What term describes the brain''s ability to form new connections throughout life?', 'Neurogenesis', 'Neuroplasticity', 'Neurotransmission', 'Neuroscience', 'b', 'The passage explicitly names this phenomenon "neuroplasticity".', 'medium'),
  ('Passage: "The human brain contains approximately 86 billion neurons, each connected to thousands of others through synapses. This vast network allows the brain to process information, store memories, and control bodily functions. Recent research suggests the brain continues to form new neural connections throughout a person''s life, a phenomenon known as neuroplasticity." Question: What does the brain''s neural network allow it to do, according to the passage?', 'Only process information', 'Process information, store memories, and control bodily functions', 'Only store memories', 'Only control bodily functions', 'b', 'The passage lists all three functions together.', 'medium'),
  ('Passage: "The human brain contains approximately 86 billion neurons, each connected to thousands of others through synapses. This vast network allows the brain to process information, store memories, and control bodily functions. Recent research suggests the brain continues to form new neural connections throughout a person''s life, a phenomenon known as neuroplasticity." Question: When does neuroplasticity occur, according to the passage?', 'Only in childhood', 'Only in old age', 'Throughout a person''s life', 'Only during sleep', 'c', 'The passage states new connections form "throughout a person''s life".', 'easy'),
  ('Passage: "Urban farming has gained popularity in recent years as cities seek sustainable ways to produce food closer to consumers. Rooftop gardens, vertical farms, and community plots allow residents to grow vegetables even in densely populated areas. Proponents argue that urban farming reduces transportation costs, provides fresher produce, and strengthens community bonds." Question: What is one benefit of urban farming mentioned in the passage?', 'Increases pollution', 'Reduces transportation costs', 'Increases food prices', 'Reduces community bonds', 'b', 'The passage explicitly lists reduced transportation costs as a benefit.', 'easy'),
  ('Passage: "Urban farming has gained popularity in recent years as cities seek sustainable ways to produce food closer to consumers. Rooftop gardens, vertical farms, and community plots allow residents to grow vegetables even in densely populated areas. Proponents argue that urban farming reduces transportation costs, provides fresher produce, and strengthens community bonds." Question: Where can urban farming take place, according to the passage?', 'Only in rural areas', 'Rooftop gardens, vertical farms, and community plots', 'Only underground', 'Only in greenhouses', 'b', 'The passage explicitly names these three locations.', 'easy'),
  ('Passage: "Urban farming has gained popularity in recent years as cities seek sustainable ways to produce food closer to consumers. Rooftop gardens, vertical farms, and community plots allow residents to grow vegetables even in densely populated areas. Proponents argue that urban farming reduces transportation costs, provides fresher produce, and strengthens community bonds." Question: What do proponents claim urban farming strengthens?', 'Government policy', 'Community bonds', 'International trade', 'Stock markets', 'b', 'The passage states urban farming "strengthens community bonds".', 'easy'),
  ('Passage: "Urban farming has gained popularity in recent years as cities seek sustainable ways to produce food closer to consumers. Rooftop gardens, vertical farms, and community plots allow residents to grow vegetables even in densely populated areas. Proponents argue that urban farming reduces transportation costs, provides fresher produce, and strengthens community bonds." Question: Why has urban farming gained popularity, according to the passage?', 'Cities seek sustainable ways to produce food closer to consumers', 'Farmers want to move to cities', 'Rural land has become expensive', 'Governments have banned rural farming', 'a', 'The passage directly states this reason.', 'medium'),
  ('Passage: "Urban farming has gained popularity in recent years as cities seek sustainable ways to produce food closer to consumers. Rooftop gardens, vertical farms, and community plots allow residents to grow vegetables even in densely populated areas. Proponents argue that urban farming reduces transportation costs, provides fresher produce, and strengthens community bonds." Question: Besides reduced transportation costs, what else does urban farming provide, according to the passage?', 'Cheaper labor', 'Fresher produce', 'More farmland', 'Better weather', 'b', 'The passage lists "fresher produce" as another benefit.', 'easy'),
  ('Passage: "The invention of the printing press by Johannes Gutenberg in the 15th century revolutionized the spread of information. Before its invention, books were copied by hand, a slow and expensive process that limited literacy to a small elite. The printing press made books more affordable and accessible, increasing literacy rates across Europe." Question: Who invented the printing press, according to the passage?', 'Johannes Gutenberg', 'Leonardo da Vinci', 'Isaac Newton', 'Galileo Galilei', 'a', 'The passage names Johannes Gutenberg as the inventor.', 'easy'),
  ('Passage: "The invention of the printing press by Johannes Gutenberg in the 15th century revolutionized the spread of information. Before its invention, books were copied by hand, a slow and expensive process that limited literacy to a small elite. The printing press made books more affordable and accessible, increasing literacy rates across Europe." Question: In which century was the printing press invented?', '13th century', '14th century', '15th century', '16th century', 'c', 'The passage states it was invented "in the 15th century".', 'easy'),
  ('Passage: "The invention of the printing press by Johannes Gutenberg in the 15th century revolutionized the spread of information. Before its invention, books were copied by hand, a slow and expensive process that limited literacy to a small elite. The printing press made books more affordable and accessible, increasing literacy rates across Europe." Question: How were books produced before the printing press?', 'Printed digitally', 'Copied by hand', 'Imported from Asia', 'Not produced at all', 'b', 'The passage states books "were copied by hand" before the printing press.', 'easy'),
  ('Passage: "The invention of the printing press by Johannes Gutenberg in the 15th century revolutionized the spread of information. Before its invention, books were copied by hand, a slow and expensive process that limited literacy to a small elite. The printing press made books more affordable and accessible, increasing literacy rates across Europe." Question: What effect did the printing press have on literacy, according to the passage?', 'It decreased literacy rates', 'It had no effect on literacy', 'It increased literacy rates', 'It only affected numeracy', 'c', 'The passage states it resulted in "increasing literacy rates across Europe".', 'easy'),
  ('Passage: "The invention of the printing press by Johannes Gutenberg in the 15th century revolutionized the spread of information. Before its invention, books were copied by hand, a slow and expensive process that limited literacy to a small elite. The printing press made books more affordable and accessible, increasing literacy rates across Europe." Question: What was limited to a small elite before the printing press?', 'Literacy', 'Farming', 'Trade', 'Travel', 'a', 'The passage states hand-copying "limited literacy to a small elite".', 'medium'),
  ('Passage: "Coral reefs, often called the ''rainforests of the sea,'' support approximately 25% of all marine species despite covering less than 1% of the ocean floor. Rising ocean temperatures due to climate change have led to widespread coral bleaching, a process in which corals expel the algae living in their tissues, causing them to turn white." Question: What percentage of marine species do coral reefs support, according to the passage?', '10%', '15%', '25%', '50%', 'c', 'The passage states reefs "support approximately 25% of all marine species".', 'easy'),
  ('Passage: "Coral reefs, often called the ''rainforests of the sea,'' support approximately 25% of all marine species despite covering less than 1% of the ocean floor. Rising ocean temperatures due to climate change have led to widespread coral bleaching, a process in which corals expel the algae living in their tissues, causing them to turn white." Question: What percentage of the ocean floor do coral reefs cover?', 'Less than 1%', 'About 10%', 'About 25%', 'About 50%', 'a', 'The passage states reefs cover "less than 1% of the ocean floor".', 'easy'),
  ('Passage: "Coral reefs, often called the ''rainforests of the sea,'' support approximately 25% of all marine species despite covering less than 1% of the ocean floor. Rising ocean temperatures due to climate change have led to widespread coral bleaching, a process in which corals expel the algae living in their tissues, causing them to turn white." Question: What causes coral bleaching, according to the passage?', 'Overfishing', 'Rising ocean temperatures', 'Ship traffic', 'Low tide', 'b', 'The passage attributes bleaching to "rising ocean temperatures due to climate change".', 'easy'),
  ('Passage: "Coral reefs, often called the ''rainforests of the sea,'' support approximately 25% of all marine species despite covering less than 1% of the ocean floor. Rising ocean temperatures due to climate change have led to widespread coral bleaching, a process in which corals expel the algae living in their tissues, causing them to turn white." Question: What happens to corals during bleaching, according to the passage?', 'They grow faster', 'They expel algae and turn white', 'They multiply rapidly', 'They change color to bright red', 'b', 'The passage describes corals expelling "the algae living in their tissues, causing them to turn white".', 'medium'),
  ('Passage: "Coral reefs, often called the ''rainforests of the sea,'' support approximately 25% of all marine species despite covering less than 1% of the ocean floor. Rising ocean temperatures due to climate change have led to widespread coral bleaching, a process in which corals expel the algae living in their tissues, causing them to turn white." Question: What nickname is given to coral reefs in the passage?', 'Gardens of the ocean', 'Rainforests of the sea', 'Cities of the deep', 'Forests of coral', 'b', 'The passage explicitly calls them the "rainforests of the sea".', 'easy')
) as q(question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
where topics.slug = 'reading-comprehension';

-- ============================================================
-- Verbal Ability > Fill in the Blanks
-- ============================================================
insert into public.questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
select id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_option, q.explanation, q.difficulty
from public.topics, (values
  ('She has been living in London ____ 2015.', 'since', 'for', 'from', 'at', 'a', 'A specific starting point in time takes "since": "since 2015".', 'easy'),
  ('He is good ____ mathematics.', 'in', 'at', 'on', 'with', 'b', '"Good" is followed by "at" for skills: "good at mathematics".', 'easy'),
  ('I am looking forward ____ meeting you.', 'for', 'at', 'to', 'with', 'c', '"Looking forward" is followed by "to" plus a gerund: "looking forward to meeting".', 'medium'),
  ('She is married ____ a doctor.', 'with', 'to', 'for', 'at', 'd', '"Married" is followed by "to": "married to a doctor".', 'medium'),
  ('He apologized ____ being late.', 'to', 'for', 'about', 'with', 'b', '"Apologize" is followed by "for": "apologized for being late".', 'easy'),
  ('They arrived ____ the airport on time.', 'to', 'at', 'in', 'on', 'b', '"Arrive" takes "at" for a specific point/building: "arrived at the airport".', 'easy'),
  ('I have been waiting ____ two hours.', 'since', 'for', 'from', 'at', 'c', 'A duration takes "for": "waiting for two hours".', 'easy'),
  ('She is capable ____ handling the situation.', 'for', 'of', 'to', 'with', 'd', '"Capable" is followed by "of" plus a gerund: "capable of handling".', 'medium'),
  ('He insisted ____ paying the bill.', 'to', 'on', 'for', 'at', 'b', '"Insist" is followed by "on" plus a gerund: "insisted on paying".', 'medium'),
  ('The teacher explained the topic ____ the students.', 'for', 'to', 'at', 'with', 'b', '"Explain" takes the object after "to": "explained the topic to the students".', 'medium'),
  ('He is afraid ____ spiders.', 'from', 'with', 'of', 'at', 'c', '"Afraid" is followed by "of": "afraid of spiders".', 'easy'),
  ('She succeeded ____ passing the exam.', 'at', 'in', 'to', 'on', 'd', '"Succeed" is followed by "in" plus a gerund: "succeeded in passing".', 'medium'),
  ('They congratulated him ____ his success.', 'on', 'for', 'at', 'with', 'a', '"Congratulate" is followed by "on": "congratulated him on his success".', 'medium'),
  ('I am interested ____ learning new languages.', 'at', 'in', 'to', 'for', 'b', '"Interested" is followed by "in": "interested in learning".', 'easy'),
  ('He was accused ____ theft.', 'for', 'with', 'of', 'at', 'c', '"Accused" is followed by "of": "accused of theft".', 'medium'),
  ('She is proud ____ her achievements.', 'for', 'at', 'with', 'of', 'd', '"Proud" is followed by "of": "proud of her achievements".', 'easy'),
  ('The children were fond ____ chocolates.', 'for', 'of', 'with', 'at', 'b', '"Fond" is followed by "of": "fond of chocolates".', 'easy'),
  ('He depends ____ his parents for financial support.', 'on', 'both on and upon are acceptable', 'upon', 'at', 'b', '"Depend" can correctly take either "on" or "upon"; both are standard usage.', 'medium'),
  ('She was absent ____ school yesterday.', 'at', 'in', 'from', 'of', 'c', '"Absent" is followed by "from": "absent from school".', 'easy'),
  ('I agree ____ your opinion.', 'to', 'for', 'at', 'with', 'd', '"Agree" is followed by "with" for a person or opinion: "agree with your opinion".', 'easy'),
  ('He is skilled ____ playing the guitar.', 'at', 'for', 'to', 'with', 'a', '"Skilled" is followed by "at": "skilled at playing".', 'medium'),
  ('They were surprised ____ the news.', 'for', 'at', 'to', 'with', 'b', '"Surprised" is followed by "at": "surprised at the news".', 'easy'),
  ('She is known ____ her honesty.', 'to', 'at', 'for', 'with', 'c', '"Known" is followed by "for" a quality: "known for her honesty".', 'medium'),
  ('He was blamed ____ the accident.', 'of', 'at', 'with', 'for', 'd', '"Blamed" is followed by "for": "blamed for the accident".', 'medium'),
  ('I am tired ____ waiting.', 'of', 'from', 'at', 'with', 'a', '"Tired" is followed by "of" for something ongoing: "tired of waiting".', 'easy')
) as q(question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
where topics.slug = 'fill-in-the-blanks';
