-- seed_16_reasoning_batch6.sql
-- Completes the Logical Reasoning category. Adds 25 questions each for
-- Syllogisms and Seating Arrangement, the two topics that had zero
-- questions. This finishes all 12 Logical Reasoning topics at 25+
-- questions each. Additive only; safe to run once after
-- seed_15_reasoning_batch5.sql.

-- ============================================================
-- Logical Reasoning > Syllogisms
-- Format: two statements, two numbered conclusions; determine which
-- conclusion(s) validly follow using standard categorical syllogism
-- rules (All/No/Some).
-- ============================================================
insert into public.questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
select id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_option, q.explanation, q.difficulty
from public.topics, (values
  ('Statements: All roses are flowers. All flowers are plants. Conclusions: I. All roses are plants. II. All plants are roses.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'a', 'By transitivity (Barbara), I is valid; II reverses the relationship and is not valid.', 'medium'),
  ('Statements: Some doctors are engineers. All engineers are educated. Conclusions: I. Some doctors are educated. II. All doctors are educated.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'a', 'I follows validly; II overstates the conclusion beyond what the premises support.', 'medium'),
  ('Statements: No cats are dogs. All dogs are animals. Conclusions: I. No cats are animals. II. Some animals are not cats.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'b', 'I does not follow (cats could still be animals); II follows because dogs, being animals that are not cats, show some animals are not cats.', 'hard'),
  ('Statements: All pens are objects. Some objects are expensive. Conclusions: I. Some pens are expensive. II. All expensive things are pens.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'd', 'The middle term "objects" is not distributed appropriately, so neither conclusion follows.', 'hard'),
  ('Statements: All teachers are graduates. Some graduates are researchers. Conclusions: I. Some teachers are researchers. II. Some researchers are teachers.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'd', 'This is a classic undistributed-middle case; neither conclusion validly follows.', 'hard'),
  ('Statements: No fruits are vegetables. All apples are fruits. Conclusions: I. No apples are vegetables. II. Some apples are not vegetables.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'c', 'I follows validly; II follows as a weaker restatement of I, since apples exist.', 'medium'),
  ('Statements: All birds are animals. Some animals are wild. Conclusions: I. Some birds are wild. II. All animals are birds.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'd', 'Undistributed middle again; neither conclusion validly follows.', 'medium'),
  ('Statements: Some pens are red. All red things are objects. Conclusions: I. Some pens are objects. II. All objects are pens.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'a', 'I follows validly; II overstates the conclusion.', 'medium'),
  ('Statements: All squares are rectangles. All rectangles are quadrilaterals. Conclusions: I. All squares are quadrilaterals. II. Some quadrilaterals are squares.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'c', 'I follows by transitivity; II follows as a particular conversion of I.', 'medium'),
  ('Statements: No students are lazy. Some lazy people are rich. Conclusions: I. No students are rich. II. Some rich people are not students.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'b', 'I does not follow (only some rich people are excluded, not all); II follows since the lazy-rich people are not students.', 'hard'),
  ('Statements: All rivers have water. Some lakes have water. Conclusions: I. Some lakes are rivers. II. All rivers are lakes.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'd', 'Undistributed middle; neither conclusion validly follows.', 'medium'),
  ('Statements: All mangoes are sweet. All sweet things are liked by children. Conclusions: I. All mangoes are liked by children. II. Some things liked by children are mangoes.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'c', 'I follows by transitivity; II follows as a particular conversion of I.', 'medium'),
  ('Statements: Some actors are singers. No singers are directors. Conclusions: I. Some actors are not directors. II. No actors are directors.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'a', 'I follows since the actor-singers are not directors; II overstates the conclusion to all actors.', 'hard'),
  ('Statements: All computers are machines. No machines are living things. Conclusions: I. No computers are living things. II. Some living things are not computers.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'a', 'I follows validly; II is not a strict logical consequence of the premises.', 'hard'),
  ('Statements: Some flowers are red. Some red things are fragrant. Conclusions: I. Some flowers are fragrant. II. All fragrant things are flowers.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'd', 'Two particular premises yield no valid conclusion.', 'hard'),
  ('Statements: All doctors are professionals. Some professionals are wealthy. Conclusions: I. Some doctors are wealthy. II. All professionals are doctors.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'd', 'Undistributed middle; neither conclusion validly follows.', 'medium'),
  ('Statements: No insects are mammals. All bees are insects. Conclusions: I. No bees are mammals. II. Some bees are not mammals.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'c', 'I follows validly; II follows as a weaker restatement of I.', 'medium'),
  ('Statements: All chairs are furniture. Some furniture is wooden. Conclusions: I. Some chairs are wooden. II. All furniture is wooden.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'd', 'Undistributed middle; neither conclusion validly follows.', 'medium'),
  ('Statements: Some pilots are engineers. All engineers are graduates. Conclusions: I. Some pilots are graduates. II. All pilots are graduates.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'a', 'I follows validly; II overstates the conclusion.', 'medium'),
  ('Statements: All lions are carnivores. No carnivores are herbivores. Conclusions: I. No lions are herbivores. II. Some herbivores are not lions.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'a', 'I follows validly; II is not a strict logical consequence.', 'hard'),
  ('Statements: Some books are novels. Some novels are bestsellers. Conclusions: I. Some books are bestsellers. II. All bestsellers are books.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'd', 'Two particular premises yield no valid conclusion.', 'hard'),
  ('Statements: All soldiers are disciplined. All disciplined people are respected. Conclusions: I. All soldiers are respected. II. Some respected people are soldiers.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'c', 'I follows by transitivity; II follows as a particular conversion of I.', 'medium'),
  ('Statements: No plants are animals. All trees are plants. Conclusions: I. No trees are animals. II. Some animals are not trees.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'c', 'I follows validly; II follows as a weaker restatement of I.', 'medium'),
  ('Statements: Some teachers are artists. No artists are dishonest. Conclusions: I. Some teachers are not dishonest. II. No teachers are dishonest.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'a', 'I follows since the teacher-artists are not dishonest; II overstates the conclusion to all teachers.', 'hard'),
  ('Statements: All windows are glass. Some glass is fragile. Conclusions: I. Some windows are fragile. II. All glass is fragile.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'd', 'Undistributed middle; neither conclusion validly follows.', 'medium')
) as q(question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
where topics.slug = 'syllogisms';

-- ============================================================
-- Logical Reasoning > Seating Arrangement
-- ============================================================
insert into public.questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
select id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_option, q.explanation, q.difficulty
from public.topics, (values
  ('Five people A, B, C, D, E sit in a row facing north. B is immediately right of A. C is immediately left of D. E is at the extreme right end. D is second from the left. What is A''s position from the left?', '1st', '2nd', '3rd', '4th', 'c', 'D=2nd, so C=1st. E=5th (extreme right). Remaining A,B fill 3rd,4th with B right of A: A=3rd, B=4th.', 'hard'),
  ('Seven students sit in a row. Raju is exactly in the middle (position 4). Sita is 2 places to the left of Raju. Find Sita''s position.', '1st', '2nd', '3rd', '4th', 'b', 'Sita = 4 - 2 = position 2.', 'medium'),
  ('Four people A, B, C, D sit around a circular table facing the center. A sits opposite B. C sits immediately right of A. Who sits immediately left of A?', 'A', 'B', 'C', 'D', 'd', 'With opposite (B) and immediate right (C) fixed, the only remaining seat, immediate left, must be D.', 'medium'),
  ('Five people sit in a row: Esha is at the left end, Bala is immediately right of Esha, Aman is immediately right of Bala, Chetan is immediately right of Aman, and Deepa is at the right end. Who is 4th from the left?', 'Aman', 'Bala', 'Chetan', 'Deepa', 'c', 'The order is Esha, Bala, Aman, Chetan, Deepa -- the 4th position is Chetan.', 'medium'),
  ('In a row of 8 people, Vikram is 3rd from the left and Anil is 3rd from the right. How many people are between them?', '1', '2', '3', '4', 'b', 'Anil is 6th from the left (8-3+1); between positions 3 and 6 there are 2 people.', 'hard'),
  ('Six people P, Q, R, S, T, U sit around a circular table facing the center. P is 2nd to the right of Q. R is immediately left of P. S is 2nd to the left of Q. T is immediately right of S. Who sits immediately left of Q?', 'P', 'R', 'S', 'T', 'd', 'Working through the positions clockwise from Q shows T occupies the seat immediately to Q''s left.', 'hard'),
  ('In a row facing north, Meera is 6th from the left and 5th from the right. How many people are in the row?', '9', '10', '11', '12', 'b', 'Total = 6 + 5 - 1 = 10.', 'easy'),
  ('Six friends sit in a row. Karan sits 3rd from the left. Divya sits 2nd from the right. How many people are seated between Karan and Divya?', '0', '1', '2', '3', 'b', 'Divya is 5th from the left (6-2+1); between positions 3 and 5 there is 1 person.', 'medium'),
  ('Five people sit around a circular table facing the center: A, B, C, D, E. A is between B and C. D is immediately right of C. E is immediately left of B. Who sits immediately clockwise of A?', 'B', 'C', 'D', 'E', 'b', 'Working clockwise from A gives the order A, C, D, E, B, so C is immediately clockwise of A.', 'hard'),
  ('Seven people sit in a row. Neha is exactly in the middle (position 4). Raj is 3 places to the right of Neha. Find Raj''s position from the left.', '5', '6', '7', '8', 'c', 'Raj = 4 + 3 = position 7.', 'medium'),
  ('In a row of 9 people, Suman is exactly in the middle (position 5). Tara is 4 places to the left of Suman. Find Tara''s position from the left.', '1', '2', '3', '4', 'a', 'Tara = 5 - 4 = position 1.', 'medium'),
  ('In a row of 5 people, V is at the left end, W is immediately right of V, X is immediately left of Y, and Z is at the right end. Find the order from left to right.', 'V, W, X, Y, Z', 'V, X, W, Y, Z', 'W, V, X, Y, Z', 'V, W, Y, X, Z', 'a', 'V=1, W=2 (immediate right of V), and the remaining X,Y must fill 3,4 with X immediately left of Y: X=3, Y=4, Z=5.', 'medium'),
  ('In a row of 6 people, Sanjay is 2nd from the left and Meena is 2nd from the right. How many people sit to the right of Meena?', '0', '1', '2', '3', 'b', 'Meena is at position 5 (2nd from the right of 6); only 1 person (position 6) sits to her right.', 'easy'),
  ('Eight people sit in a row facing north. Aarav is 4th from the left. Bhavna is 4th from the right. How many people sit between them?', 'They are the same person', '0 people between them', '1 person between them', '2 people between them', 'b', 'Bhavna is at position 5 (8-4+1), immediately next to Aarav at position 4 -- 0 people between them.', 'medium'),
  ('In a circular arrangement of 8 people facing the center (seats numbered 1-8 clockwise), A sits 3rd to the right of B (seat 1). C sits directly opposite A. Where is C relative to B?', 'Immediately left of B', 'Immediately right of B', 'Directly opposite B', '3rd to the right of B', 'a', 'A is at seat 4; C, opposite A, is at seat 8, which is immediately to the left (counterclockwise) of B at seat 1.', 'hard'),
  ('In a row of 5 friends, Deepa is at the left end, Bala is immediately left of Anu, Chandra is immediately right of Anu, and Anu is not at either end. Find Esha''s (the fifth friend''s) position.', '1st', '2nd', '4th', '5th', 'd', 'Deepa=1st; the consecutive trio Bala, Anu, Chandra must occupy 2nd-4th, leaving Esha at the 5th (right end).', 'hard'),
  ('Five people sit around a circular table facing the center: Raj, Simran, Tanvi, Umesh, Vikas. Raj sits between Simran and Tanvi. Umesh sits immediately right of Tanvi. Vikas sits immediately left of Simran. Who sits immediately right of Umesh?', 'Raj', 'Simran', 'Tanvi', 'Vikas', 'd', 'The clockwise order works out to Vikas, Simran, Raj, Tanvi, Umesh, and back to Vikas -- so Vikas is immediately right of Umesh.', 'hard'),
  ('In a row of 7 people, the middle person (position 4) is Farah. Gaurav is 2 places to the right of Farah. Find Gaurav''s position from the right end.', '1st', '2nd', '3rd', '4th', 'b', 'Gaurav is at position 6 from the left; from the right, that is 7-6+1 = 2nd.', 'medium'),
  ('Four couples (8 people) sit around a circular table alternating men and women, facing the center. If a man sits at seat 1, is seat 3 occupied by a man or a woman?', 'Man', 'Woman', 'Cannot be determined', 'Empty seat', 'a', 'With alternating seating starting with a man at seat 1, odd-numbered seats (1,3,5,7) are all men.', 'medium'),
  ('In a row of 6 people, twins Ram and Shyam sit at the two ends, with Ram at the left end. Their friend Mohan sits 3rd from the left. Find Mohan''s position from the right end.', '2nd', '3rd', '4th', '5th', 'c', 'Mohan is 3rd from the left; from the right in a row of 6, that is 6-3+1 = 4th.', 'medium'),
  ('Five people sit in a row facing north: Om is at the left end, Manav is immediately left of Leela, Kavita is immediately right of Leela, and Nisha is at the right end. Find the order from left to right.', 'Om, Manav, Leela, Kavita, Nisha', 'Om, Leela, Manav, Kavita, Nisha', 'Manav, Om, Leela, Kavita, Nisha', 'Om, Manav, Kavita, Leela, Nisha', 'a', 'Om=1st, Nisha=5th, and the consecutive trio Manav, Leela, Kavita fills positions 2-4 in that order.', 'medium'),
  ('Nine people sit in a row. The middle person (position 5) is Priya. Rakesh sits 4 places to the left of Priya. Find Rakesh''s position from the left end.', '1', '2', '3', '4', 'a', 'Rakesh = 5 - 4 = position 1.', 'medium'),
  ('In a circular arrangement of 6 people facing the center (seats numbered 1-6 clockwise), Aditi sits at seat 2. Bhanu sits directly opposite Aditi. At which seat does Bhanu sit?', '4', '5', '6', '1', 'b', 'Opposite in a 6-seat circle means 3 seats away: 2+3 = seat 5.', 'medium'),
  ('In a row of 10 people, Tina is 6th from the left. If 4 people are removed from the right end (none of them Tina), what is Tina''s new position from the right end?', '1st', '2nd', '3rd', '4th', 'a', 'The new row has 6 people, and Tina, still at position 6 from the left, is now 1st from the right.', 'hard'),
  ('Eight friends sit around a circular table facing the center, seats numbered 1-8 clockwise. Arjun sits at seat 1. Bina sits 4 seats clockwise from Arjun. Chetan sits immediately counterclockwise of Bina. At which seat does Chetan sit?', '3', '4', '5', '6', 'b', 'Bina is at seat 5 (1+4); Chetan, immediately counterclockwise, is at seat 4.', 'hard')
) as q(question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
where topics.slug = 'seating-arrangement';
