-- seed_15_reasoning_batch5.sql
-- Continues the topic-expansion pass for Logical Reasoning. Tops up
-- Statement and Conclusion, Cause and Effect, and Puzzle Test (each
-- originally seeded with 6 questions in seed_03) with 19 more each to
-- reach 25. Additive only; safe to run once after seed_14_reasoning_batch4.sql.

-- ============================================================
-- Logical Reasoning > Statement and Conclusion (top-up)
-- ============================================================
insert into public.questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
select id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_option, q.explanation, q.difficulty
from public.topics, (values
  ('Statements: All cats are animals. All animals need food. Which conclusion follows?', 'No conclusion follows', 'All cats need food', 'All animals are cats', 'Some cats don''t need food', 'b', 'By transitivity, since all cats are animals and all animals need food, all cats need food.', 'easy'),
  ('Statements: No fish are mammals. All whales are mammals. Which conclusion follows?', 'No whales are fish', 'Some whales are fish', 'All fish are whales', 'No conclusion follows', 'a', 'Since whales are mammals and no mammals are fish, no whales are fish.', 'medium'),
  ('Statements: Some engineers are doctors. All doctors are graduates. Which conclusion follows?', 'All engineers are graduates', 'No engineers are graduates', 'Some engineers are graduates', 'All graduates are engineers', 'c', 'Since some engineers are doctors, and all doctors are graduates, some engineers are graduates.', 'medium'),
  ('Statements: All pens are instruments. Some instruments are expensive. Which conclusion follows?', 'All pens are expensive', 'Some pens are expensive', 'No pens are expensive', 'No definite conclusion can be drawn', 'd', 'The statements don''t guarantee any pen is among the expensive instruments.', 'hard'),
  ('Statements: All mangoes are fruits. All fruits are healthy. Which conclusion follows?', 'All mangoes are healthy', 'No mangoes are healthy', 'Some fruits are mangoes', 'No conclusion follows', 'a', 'By transitivity, all mangoes are healthy.', 'easy'),
  ('Statements: Some books are pens. All pens are metallic. Which conclusion follows?', 'No conclusion follows', 'Some books are metallic', 'All books are metallic', 'No books are metallic', 'b', 'Since some books are pens, and all pens are metallic, some books are metallic.', 'medium'),
  ('Statements: All doctors are educated. Raj is a doctor. Which conclusion follows?', 'Raj is not educated', 'Raj is a teacher', 'Raj is educated', 'No conclusion follows', 'c', 'Since Raj is a doctor and all doctors are educated, Raj is educated.', 'easy'),
  ('Statements: No teachers are lazy. Some lazy people are students. Which conclusion follows?', 'No students are teachers', 'Some students are not teachers', 'All students are teachers', 'No conclusion follows', 'b', 'Since some lazy people are students, and no teachers are lazy, those particular students are not teachers.', 'hard'),
  ('Statements: All circles are round. Some round objects are balls. Which conclusion follows?', 'All circles are balls', 'Some circles are balls', 'No circles are balls', 'No definite conclusion can be drawn', 'd', 'The statements don''t guarantee any circle is among the round objects that are balls.', 'hard'),
  ('Statements: All soldiers are brave. Some brave people are famous. Which conclusion follows?', 'All soldiers are famous', 'Some soldiers are famous', 'No soldiers are famous', 'No definite conclusion can be drawn', 'd', 'The statements don''t guarantee any soldier is among the famous brave people.', 'hard'),
  ('Statements: All apples are red. This fruit is an apple. Which conclusion follows?', 'This fruit is red', 'This fruit is not red', 'This fruit is a mango', 'No conclusion follows', 'a', 'Since this fruit is an apple and all apples are red, this fruit is red.', 'easy'),
  ('Statements: Some students are athletes. All athletes are fit. Which conclusion follows?', 'All students are fit', 'Some students are fit', 'No students are fit', 'No conclusion follows', 'b', 'Since some students are athletes, and all athletes are fit, some students are fit.', 'medium'),
  ('Statements: No metals are liquid at room temperature except mercury. Mercury is a metal. Which conclusion follows?', 'Mercury is liquid at room temperature', 'Mercury is not a metal', 'All metals are liquid', 'No conclusion follows', 'a', 'The statement explicitly makes mercury the exception, so mercury is liquid at room temperature.', 'medium'),
  ('Statements: All rivers flow to the sea. The Ganges is a river. Which conclusion follows?', 'The Ganges flows to the sea', 'The Ganges does not flow to the sea', 'The Ganges is not a river', 'No conclusion follows', 'a', 'Since the Ganges is a river and all rivers flow to the sea, the Ganges flows to the sea.', 'easy'),
  ('Statements: Some tools are sharp. All sharp things are dangerous. Which conclusion follows?', 'No conclusion follows', 'Some tools are dangerous', 'All tools are dangerous', 'No tools are dangerous', 'b', 'Since some tools are sharp, and all sharp things are dangerous, some tools are dangerous.', 'medium'),
  ('Statements: All planets orbit the sun. Earth is a planet. Which conclusion follows?', 'Earth orbits the sun', 'Earth does not orbit the sun', 'Earth is a star', 'No conclusion follows', 'a', 'Since Earth is a planet and all planets orbit the sun, Earth orbits the sun.', 'easy'),
  ('Statements: No reptiles are warm-blooded. All snakes are reptiles. Which conclusion follows?', 'All snakes are warm-blooded', 'No snakes are warm-blooded', 'Some snakes are warm-blooded', 'No conclusion follows', 'b', 'Since snakes are reptiles and no reptiles are warm-blooded, no snakes are warm-blooded.', 'medium'),
  ('Statements: All students in the hostel are disciplined. Some disciplined people are scholars. Which conclusion follows?', 'All hostel students are scholars', 'Some hostel students are scholars', 'No hostel students are scholars', 'No definite conclusion can be drawn', 'd', 'The statements don''t guarantee any hostel student is among the disciplined people who are scholars.', 'hard'),
  ('Statements: All squares have four equal sides. This shape has four equal sides. Which conclusion follows?', 'This shape is definitely a square', 'This shape is definitely not a square', 'No definite conclusion can be drawn about it being a square', 'This shape is a triangle', 'c', 'Having four equal sides doesn''t guarantee a square (a rhombus also qualifies), so no definite conclusion follows.', 'hard')
) as q(question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
where topics.slug = 'statement-and-conclusion';

-- ============================================================
-- Logical Reasoning > Cause and Effect (top-up)
-- ============================================================
insert into public.questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
select id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_option, q.explanation, q.difficulty
from public.topics, (values
  ('I. The government announced a new tax on imported electronics. II. Prices of imported electronics rose sharply. What is the relationship?', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are independent events', 'Both are effects of a common cause', 'a', 'The tax (I) directly drives up prices (II).', 'easy'),
  ('I. A bridge collapsed during rush hour. II. Traffic was diverted to alternate routes for weeks. What is the relationship?', 'II is the cause, I is the effect', 'I is the cause, II is the effect', 'Both are independent events', 'Both are effects of a common cause', 'b', 'The bridge collapse (I) forces the traffic diversion (II).', 'easy'),
  ('I. Heavy snowfall blocked the mountain roads. II. Several villages were cut off from supplies for days. What is the relationship?', 'Both are independent events', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are effects of a common cause', 'b', 'The blocked roads (I) directly cause the villages to be cut off (II).', 'easy'),
  ('I. The company launched a loyalty rewards program. II. Customer retention rates improved significantly. What is the relationship?', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are independent events', 'Both are effects of a common cause', 'a', 'The rewards program (I) drives the improved retention (II).', 'medium'),
  ('I. There was a sudden drop in temperature overnight. II. Many crops were damaged by frost. What is the relationship?', 'II is the cause, I is the effect', 'I is the cause, II is the effect', 'Both are independent events', 'Both are effects of a common cause', 'b', 'The temperature drop (I) causes the frost damage (II).', 'easy'),
  ('I. Enrollment in an online course doubled this year. II. The course fee was reduced by 50%. What is the relationship?', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are independent events', 'Both are effects of a common cause', 'b', 'The fee reduction (II) drives the increased enrollment (I).', 'medium'),
  ('I. The city implemented a new recycling program. II. The amount of waste sent to landfills decreased. What is the relationship?', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are independent events', 'Both are effects of a common cause', 'a', 'The recycling program (I) reduces landfill waste (II).', 'easy'),
  ('I. A popular celebrity endorsed a new smartphone brand. II. Sales of the smartphone brand increased significantly. What is the relationship?', 'Both are independent events', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are effects of a common cause', 'b', 'The endorsement (I) drives the sales increase (II).', 'medium'),
  ('I. Air pollution levels in the city increased. II. Respiratory illness cases rose in the same period. What is the relationship?', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are independent events', 'Both are effects of a common cause', 'a', 'Increased pollution (I) contributes to more respiratory illness (II).', 'medium'),
  ('I. An airline reduced the number of daily flights on a route. II. Ticket prices for that route increased. What is the relationship?', 'II is the cause, I is the effect', 'I is the cause, II is the effect', 'Both are independent events', 'Both are effects of a common cause', 'b', 'Reduced supply of flights (I) drives up ticket prices (II).', 'medium'),
  ('I. A new highway was constructed connecting two cities. II. Travel time between the cities was significantly reduced. What is the relationship?', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are independent events', 'Both are effects of a common cause', 'a', 'The new highway (I) causes reduced travel time (II).', 'easy'),
  ('I. A company reduced its workforce by 20%. II. The company''s operating costs decreased. What is the relationship?', 'II is the cause, I is the effect', 'I is the cause, II is the effect', 'Both are independent events', 'Both are effects of a common cause', 'b', 'The workforce reduction (I) causes lower operating costs (II).', 'medium'),
  ('I. A prolonged drought affected the region. II. Farmers reported significantly reduced crop yields. What is the relationship?', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are independent events', 'Both are effects of a common cause', 'a', 'The drought (I) directly causes reduced crop yields (II).', 'easy'),
  ('I. A store extended its operating hours. II. Weekly sales revenue increased. What is the relationship?', 'Both are independent events', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are effects of a common cause', 'b', 'The extended hours (I) drive the increased sales (II).', 'medium'),
  ('I. A new vaccine was introduced for a common disease. II. The number of reported cases of the disease declined sharply. What is the relationship?', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are independent events', 'Both are effects of a common cause', 'a', 'The vaccine (I) causes the decline in cases (II).', 'easy'),
  ('I. Interest rates on loans were increased by the central bank. II. Consumer borrowing and spending declined. What is the relationship?', 'II is the cause, I is the effect', 'I is the cause, II is the effect', 'Both are independent events', 'Both are effects of a common cause', 'b', 'Higher interest rates (I) discourage borrowing and spending (II).', 'medium'),
  ('I. A factory installed pollution control equipment. II. Nearby air quality improved measurably. What is the relationship?', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are independent events', 'Both are effects of a common cause', 'a', 'The pollution control equipment (I) causes the improved air quality (II).', 'easy'),
  ('I. A power outage affected the entire city. II. Traffic signals stopped working, causing congestion. What is the relationship?', 'Both are independent events', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are effects of a common cause', 'b', 'The power outage (I) causes the traffic signal failure and resulting congestion (II).', 'easy'),
  ('I. A school introduced a new anti-bullying policy. II. Reports of bullying incidents decreased over the semester. What is the relationship?', 'I is the cause, II is the effect', 'II is the cause, I is the effect', 'Both are independent events', 'Both are effects of a common cause', 'a', 'The new policy (I) causes the decline in bullying incidents (II).', 'medium')
) as q(question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
where topics.slug = 'cause-and-effect';

-- ============================================================
-- Logical Reasoning > Puzzle Test (top-up)
-- ============================================================
insert into public.questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
select id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_option, q.explanation, q.difficulty
from public.topics, (values
  ('Five friends P, Q, R, S, T stand in a line. P is left of Q. R is right of S. T is between Q and R. S is at the left end. Find the order from left to right.', 'S, P, Q, T, R', 'P, S, Q, T, R', 'S, Q, P, T, R', 'S, P, T, Q, R', 'a', 'Placing S first, then P, Q, T, R satisfies all constraints: P left of Q, T between Q and R, R right of S.', 'hard'),
  ('Four friends A, B, C, D sit around a circular table facing the center. A is opposite C. B is immediately right of A. Who is immediately left of A?', 'A', 'B', 'C', 'D', 'd', 'With only 4 people, once opposite (C) and immediate right (B) are fixed, the remaining seat (immediate left) must be D.', 'medium'),
  ('In a row, Aman is 3rd from the left and Bina is 4th from the right, with exactly 2 people between them. How many people are in the row?', '7', '8', '9', '10', 'c', 'If Bina''s position from the left is x, then x-3-1=2 gives x=6, and since she is 4th from the right, total = 6+4-1 = 9.', 'hard'),
  ('Five boxes are stacked. Box A is above box B. Box C is below box D. Box E is at the very bottom. Box B is directly above box E. Find the box at the top.', 'A', 'B', 'C', 'D', 'a', 'Stacking bottom to top as E, B, C, D, A satisfies all constraints, putting A at the top.', 'hard'),
  ('Rohan ranks 7th from the top and 18th from the bottom in his class. How many students are in the class?', '22', '23', '24', '25', 'c', 'Total = 7 + 18 - 1 = 24.', 'easy'),
  ('A, B, C, D, and E are five friends of different heights. A is taller than B but shorter than C. D is the tallest. E is shorter than B. Who is the second tallest?', 'A', 'B', 'C', 'D', 'c', 'The order is D > C > A > B > E, so C is second tallest.', 'medium'),
  ('In a row of 20 children, Meena is 5th from the left and Reena is 8th from the right. How many children are between them?', '5', '6', '7', '8', 'c', 'Meena is at position 5; Reena, 8th from the right, is at position 13. Between them: 13-5-1 = 7.', 'hard'),
  ('Four people P, Q, R, S have different heights. P is taller than Q but shorter than R. S is the shortest. Who is the tallest?', 'P', 'Q', 'R', 'S', 'c', 'The order is R > P > Q > S, so R is tallest.', 'easy'),
  ('In a row of 8 people, A sits third to the left of B. C sits second to the right of B. D sits immediately right of C. If A is at the leftmost end (position 1), find C''s position.', '5', '6', '7', '8', 'b', 'B is at position 4 (A+3); C is 2 to the right of B, at position 6.', 'medium'),
  ('Six friends sit in a row: Rahul is at the left end, Kiran is between Rahul and Sonia, Priya is next to Sonia, and Anita is between Priya and Vikram. Find the order from left to right.', 'Rahul, Kiran, Sonia, Priya, Anita, Vikram', 'Rahul, Sonia, Kiran, Priya, Anita, Vikram', 'Rahul, Kiran, Priya, Sonia, Anita, Vikram', 'Rahul, Kiran, Sonia, Anita, Priya, Vikram', 'a', 'Placing them in this order satisfies all the given adjacency constraints.', 'hard'),
  ('In a family, A is married to B. C is the son of A. D is the daughter of B. E is the mother of A. How is E related to C?', 'Mother', 'Grandmother', 'Aunt', 'Sister', 'b', 'E is A''s mother, and C is A''s child, so E is C''s grandmother.', 'medium'),
  ('Five books P, Q, R, S, T are on a shelf. P is left of Q but right of R. S is at the right end. T is left of R. Find the leftmost book.', 'P', 'Q', 'R', 'T', 'd', 'The order T, R, P, Q, S satisfies all constraints, putting T leftmost.', 'hard'),
  ('In a row of 10 students, Vikas is 4th from the left and Nisha is 4th from the right. How many students are between them?', '1', '2', '3', '4', 'b', 'Nisha is at position 7 (10-4+1); between positions 4 and 7 there are 2 students.', 'medium'),
  ('Four friends are ranked in a competition. A ranked better than C. B ranked worse than D but better than A. Who ranked the best?', 'A', 'B', 'C', 'D', 'd', 'The order is D > B > A > C, so D ranked best.', 'medium'),
  ('Suresh is 10th from the front and 15th from the back of a queue. How many people are in the queue?', '22', '23', '24', '25', 'c', 'Total = 10 + 15 - 1 = 24.', 'easy'),
  ('Four people sit around a circular table facing the center: Amit, Bala, Chetan, Deepak. Amit is opposite Chetan. Bala is immediately right of Amit. Who is immediately left of Amit?', 'Bala', 'Chetan', 'Deepak', 'Amit', 'c', 'With opposite (Chetan) and immediate right (Bala) fixed, the remaining person, Deepak, must be immediately left.', 'medium'),
  ('Five flags are arranged in a row: the red flag is at one end, the blue flag is immediately next to it, the green flag is in the middle, the yellow flag is immediately next to green, and the white flag is at the other end. Find the arrangement.', 'Red, Blue, Green, Yellow, White', 'Red, Green, Blue, Yellow, White', 'White, Blue, Green, Yellow, Red', 'Red, Blue, Yellow, Green, White', 'a', 'This order satisfies all the given adjacency and end-position constraints.', 'medium'),
  ('Four cousins A, B, C, D have different ages. A is older than B. C is younger than D but older than A. Who is the youngest?', 'A', 'B', 'C', 'D', 'b', 'The order is D > C > A > B, so B is youngest.', 'medium'),
  ('In a row of 12 people, Manoj is 5th from the left. If 3 people are added to the left end, what is his new position from the left?', '6th', '7th', '8th', '9th', 'c', 'His position shifts by 3: 5+3 = 8th.', 'easy')
) as q(question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
where topics.slug = 'puzzle-test';
