-- seed_14_reasoning_batch4.sql
-- Continues the topic-expansion pass for Logical Reasoning. Tops up
-- Statement and Argument (originally seeded with 6 questions in
-- seed_03) with 19 more to reach 25.
-- Additive only; safe to run once after seed_13_reasoning_batch3.sql.

-- ============================================================
-- Logical Reasoning > Statement and Argument (top-up)
-- ============================================================
insert into public.questions (topic_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
select id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_option, q.explanation, q.difficulty
from public.topics, (values
  ('Statement: Should the government increase funding for public libraries? Which is the strongest argument in favor?', 'Libraries have nice architecture', 'Some people prefer buying books', 'Increased funding would improve access to books and educational resources for all, regardless of income', 'Libraries are quiet places', 'c', 'This is the only option presenting a substantive, relevant benefit of increased funding.', 'medium'),
  ('Statement: Should students be allowed to use calculators in all exams? Which is the strongest argument against?', 'Calculators are expensive', 'Calculators are useful in daily life', 'Unrestricted use may prevent students from mastering fundamental arithmetic skills', 'Some calculators run out of battery', 'c', 'This identifies a substantive educational drawback, unlike the other trivial points.', 'medium'),
  ('Statement: Should companies be required to give employees paid parental leave? Which is the strongest argument in favor?', 'Companies have HR departments', 'It supports family wellbeing and improves employee retention and productivity', 'Some employees don''t have children', 'Leave forms take time to process', 'b', 'This is the only option with a substantive, relevant benefit.', 'medium'),
  ('Statement: Should cities invest more in public transportation? Which is the strongest argument in favor?', 'Buses have wheels', 'Better public transit reduces traffic congestion and pollution', 'Some people like driving', 'Transit cards are convenient to carry', 'b', 'This is the only option presenting a substantive, relevant benefit.', 'easy'),
  ('Statement: Should high schools make coding a mandatory subject? Which is the strongest argument against?', 'Coding is difficult for some', 'Mandating one specific technical skill may crowd out equally valuable subjects for students with different aptitudes and career goals', 'Computers can be expensive', 'Not all schools have computer labs', 'b', 'This identifies a substantive curricular tradeoff, not a logistical inconvenience.', 'hard'),
  ('Statement: Should the legal voting age be lowered to 16? Which is the strongest argument in favor?', '16-year-olds use social media', 'Some countries have different laws', 'Younger citizens are affected by policy decisions, and engaging them early builds lifelong civic participation', 'Voting machines are electronic', 'c', 'This is the only substantive, relevant argument.', 'medium'),
  ('Statement: Should fast food advertising targeting children be banned? Which is the strongest argument in favor?', 'Fast food restaurants are popular', 'Such advertising exploits children''s inability to critically evaluate persuasive messaging, contributing to poor health outcomes', 'Some children don''t watch TV', 'Advertisements are colorful', 'b', 'This is the only option with a substantive, relevant justification.', 'medium'),
  ('Statement: Should employees be required to disclose salaries to promote pay transparency? Which is the strongest argument in favor?', 'Salary transparency helps identify and correct unfair pay gaps', 'Salaries are personal', 'Some people talk about money', 'Payroll systems are software-based', 'a', 'This directly addresses a substantive benefit of the proposed policy.', 'medium'),
  ('Statement: Should zoos be banned? Which is the strongest argument against banning them?', 'Animals are cute', 'Accredited zoos play a significant role in conservation research and breeding endangered species', 'Zoos charge entry fees', 'Some zoos have gift shops', 'b', 'This is the only substantive, relevant argument against a ban.', 'medium'),
  ('Statement: Should single-use plastics be taxed? Which is the strongest argument in favor?', 'Plastic is lightweight', 'Some stores already charge for bags', 'Taxing single-use plastics incentivizes more sustainable alternatives and reduces environmental waste', 'Taxes are unpopular', 'c', 'This directly addresses the environmental rationale for the tax.', 'medium'),
  ('Statement: Should remote job interviews permanently replace in-person interviews? Which is the strongest argument against?', 'In-person interviews allow better assessment of interpersonal skills and reduce technical mishaps that can disadvantage candidates', 'Video calls need internet', 'Some interviewers prefer coffee meetings', 'Offices have meeting rooms', 'a', 'This is the only substantive, relevant argument against the change.', 'medium'),
  ('Statement: Should universities eliminate standardized testing for admissions? Which is the strongest argument in favor?', 'Tests are taken on paper or computer', 'Standardized tests can disadvantage students without access to costly test preparation resources', 'Some students are nervous test-takers', 'Universities have admissions offices', 'b', 'This identifies a substantive equity concern with standardized testing.', 'medium'),
  ('Statement: Should countries invest more in renewable energy research? Which is the strongest argument in favor?', 'Solar panels are blue', 'Some countries have more sunlight', 'Renewable energy reduces long-term dependence on finite fossil fuels and lowers carbon emissions', 'Energy bills vary by region', 'c', 'This is the only substantive, relevant justification.', 'easy'),
  ('Statement: Should social media platforms verify the age of all users? Which is the strongest argument in favor?', 'Age verification is technically complex', 'It helps protect minors from harmful content and predatory behavior online', 'Some users lie about their age', 'Platforms have privacy policies', 'b', 'This directly addresses the child-safety rationale for verification.', 'medium'),
  ('Statement: Should companies be allowed to monitor employees'' work computers? Which is the strongest argument against?', 'Computers can be hacked', 'Constant monitoring can erode employee trust and morale, harming long-term productivity', 'Some employees use personal laptops', 'Monitoring software needs updates', 'b', 'This identifies a substantive organizational cost of pervasive monitoring.', 'hard'),
  ('Statement: Should national parks charge higher entry fees to fund conservation? Which is the strongest argument in favor?', 'Parks have trails', 'Higher fees directly fund maintenance and conservation efforts that protect these natural spaces long-term', 'Some visitors bring their own food', 'Entry fees vary by season', 'b', 'This directly ties the fee increase to a substantive conservation benefit.', 'medium'),
  ('Statement: Should schools eliminate homework for elementary students? Which is the strongest argument in favor?', 'Homework takes time', 'Reduced homework allows more time for play and family activities, which are critical for early childhood development', 'Some parents help with homework', 'Textbooks are heavy', 'b', 'This is the only substantive, developmentally grounded argument.', 'medium'),
  ('Statement: Should airlines be required to compensate passengers for significant flight delays? Which is the strongest argument in favor?', 'Airports have lounges', 'It incentivizes airlines to improve operational reliability and treats passengers fairly for disruptions within their control', 'Some delays are due to weather', 'Flights have schedules', 'b', 'This identifies a substantive fairness and accountability rationale.', 'medium'),
  ('Statement: Should companies be banned from using plastic packaging entirely? Which is the strongest argument against a total ban?', 'Plastic packaging is often cheaper', 'In some cases, like medical supplies, plastic packaging provides essential sterility and protection that alternatives cannot yet match', 'Plastic is colorful', 'Some packaging is recyclable', 'b', 'This identifies a substantive case where no adequate alternative currently exists.', 'hard')
) as q(question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty)
where topics.slug = 'statement-and-argument';
